
import { Bill } from "../types";

export const createGoogleCalendarLink = (bill: Bill): string => {
  const { staffName, description, dueDate, amount, currency } = bill;
  
  // Create start and end dates for the event (all day event on due date)
  const start = dueDate.replace(/-/g, '');
  const end = start; // Same day for due date
  
  const currencySymbol = currency === 'USD' ? '$' : 'MVR ';

  const title = encodeURIComponent(`Due: ${staffName} Bill (${currencySymbol}${amount})`);
  const details = encodeURIComponent(`Bill for ${description}. Amount: ${currencySymbol}${amount}. \nGenerated by BillTrackr Pro.`);
  const location = encodeURIComponent("Online");

  // Google Calendar Template URL
  // action=TEMPLATE
  // dates=YYYYMMDD/YYYYMMDD
  // add=user@example.com (optional)
  // sprop=website:www.billtrackr.com
  
  return `https://www.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${start}/${end}&details=${details}&location=${location}&sf=true&output=xml`;
};
